# Generated by Django 5.2.6 on 2025-09-29 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NewTask', models.CharField(max_length=50)),
                ('Description', models.CharField(max_length=150, null=True)),
            ],
        ),
    ]
