# Generated by Django 5.2.6 on 2025-09-30 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='Status',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='Description',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
