# Generated by Django 5.2.6 on 2025-09-30 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0002_tasks_status_alter_tasks_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='Status',
            field=models.CharField(),
        ),
    ]
