# Generated by Django 5.2.6 on 2025-09-30 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0003_alter_tasks_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='Status',
            field=models.CharField(max_length=50),
        ),
    ]
