# Generated by Django 5.2.6 on 2025-09-30 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0005_alter_tasks_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='Status',
        ),
    ]
