# Generated by Django 5.2.6 on 2025-09-30 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0006_remove_tasks_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='Status',
            field=models.BooleanField(null=True),
        ),
    ]
