# Generated by Django 5.2.6 on 2025-09-30 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0008_remove_tasks_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='completed',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
